### ISSUE TITLE
Does not work with Safari and on iPhone

### ISSUE THREAD

**Issue by mhauri** [matheusgrieger/vue-clazy-load#16]
Hi @matheusgrieger 
I like your lazy loader, but sadly it isn't working on Safari and on iPhones.
![screen shot 2018-08-16 at 12 33 54](https://user-images.githubusercontent.com/402069/44203820-af947d80-a150-11e8-95e0-1373fe9daaca.png)

**Comment by matheusgrieger** [comment]
Hello! It works, actually. But you have to polyfill it because the Intersection Observer API is not available in neither Safari or iPhones.

The README shows just how to do it, and you can see the lack of support [here](https://caniuse.com/#feat=intersectionobserver).

But thanks for noticing it, I'll include the polyfill in the example page as well.
